# Site settings
title: Data-centric Machine Learning Research
email: 
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlr-datasets/jekyll-theme
style: dmlr
description: > # this means to ignore newlines until "baseurl:"
  The Journal of Data-centric Machine Learning Research (DMLR) is a new member of the 
  JMLR family, aiming to provide a top archival venue for high-quality scholarly articles 
  focused on the data aspect of machine learning research. 
  
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://data.mlr.press" # the base hostname & protocol for your site
twitter_username: MLResearchPress
github_username:  mlr-datasets

ghub:
  edit: true
  repository: mlr-datasets.github.io

analytics:
  google:
    tracking_id: UA-92432422-1

# Build settings
markdown: kramdown
